name: Build
on:
  push:
    branches:
      - master
      - develop
      - release/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - name: Deploy demo
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/demo
